### PR TITLE
Adding updated plotting script

### PR DESCRIPTION
**Pull request by bryates**
This is an updated plotting script to work with `histEFT`. There are a few commented out lines that I left in for now. Some are related to rebinning, which `histEFT` does not currently support, and others are related to grouping. For the grouping, I have an different way of performing it using lines like
https://github.com/TopEFT/topeft/blob/91e48bc7435193207bd25a951accd5c6ac565c65/analysis/topeft_run2/make_cr_and_sr_plots.py#L525
Please feel free to test this and update any pieces I might have missed.

### CODE REVIEW

**Comment by anpicci** [comment]
@bryates this is the version of the script that both you and @anehnis are able to run, am I correct?

**Comment by bryates** [comment]
> @bryates this is the version of the script that both you and @anehnis are able to run, am I correct?

Correct. Commands like `python make_cr_and_sr_plots.py -f ~/../../a/aehnis/Public/debugging_full_cr_2022.pkl.gz ~/www/run3/
` should produce the plots, if you have a `run3` dir in your web area.

**Comment by anpicci** [comment]
Hi @bryates, @anehnis pushed into the `clib_run3` branch her version of the script, which looks like for her.

In the following, I am reporting the differences wrt the version of the same script from your branch, according to `git diff`:

```
$ git diff origin/new_plot_sciprt -- analysis/topeft_run2/make_cr_and_sr_plots.py
diff --git a/analysis/topeft_run2/make_cr_and_sr_plots.py b/analysis/topeft_run2/make_cr_and_sr_plots.py
index 1f4e96ee..84b6127c 100644
--- a/analysis/topeft_run2/make_cr_and_sr_plots.py
+++ b/analysis/topeft_run2/make_cr_and_sr_plots.py
@@ -1041,6 +1041,7 @@ def make_all_sr_plots(dict_of_hists,year,unit_norm_bool,save_dir_path,split_by_c
                 hist_sig_integrated_ch = hist_sig_integrated_ch.integrate("process")
 
                 # Make the plots
+                print(hist_sig_integrated_ch)
                 if not hist_sig_integrated_ch.eval({}):
                     print("Warning: empty mc histo, continuing")
                     continue
@@ -1077,10 +1078,7 @@ def make_all_sr_plots(dict_of_hists,year,unit_norm_bool,save_dir_path,split_by_c
                     # Integrate
                     hist_sig_grouped_tmp = copy.deepcopy(hist_sig_grouped)
                     hist_sig_grouped_tmp = yt.integrate_out_appl(hist_sig_grouped_tmp,grouped_hist_cat)
-                    if proc_name not in list(hist_sig_grouped_tmp.axes["process"]):
-                        print(f"Warning: mc histo missing {proc_name}, continuing")
-                        continue
-                    hist_sig_grouped_tmp = hist_sig_grouped_tmp.integrate("process",proc_name)
+                    hist_sig_grouped_tmp = hist_sig_grouped_tmp.integrate("process",proc_name[{'process': sum}])
                     if not hist_sig_grouped_tmp.eval({}):
                         print("Warning: empty mc histo, continuing")
                         continue
@@ -1122,6 +1120,9 @@ def make_all_cr_plots(dict_of_hists,year,skip_syst_errs,unit_norm_bool,save_dir_
     elif year == "2016APV":
         mc_wl.append("UL16APV")
         data_wl.append("UL16APV")
+    elif year == "2022":
+        mc_wl.append("central2022")
+        data_wl.append("2022")
     else: raise Exception(f"Error: Unknown year \"{year}\".")
 
     # Get the list of samples we want to plot
@@ -1176,6 +1177,7 @@ def make_all_cr_plots(dict_of_hists,year,skip_syst_errs,unit_norm_bool,save_dir_
     #skip_wlst = ["njets"] # Skip all but these hists
     for idx,var_name in enumerate(dict_of_hists.keys()):
         if 'sumw2' in var_name: continue
+        if 'j0' in var_name: continue
         if (var_name in skip_lst): continue
         #if (var_name not in skip_wlst): continue
         if (var_name == "njets"):
```

How do you prefer to proceed?

**Comment by anpicci** [comment]
To summarize @bryates , you are suggesting first to revert the changes in `clib_run3`, so we don't have conflicting merging, and then add the `2022` to the version of the script in this branch?

**Comment by bryates** [comment]
> To summarize @bryates , you are suggesting first to revert the changes in `clib_run3`, so we don't have conflicting merging, and then add the `2022` to the version of the script in this branch?

Correct

**Comment by anpicci** [comment]
@bryates with some GH tricks, I was able to retrieve the version in this branch and copy it into the `clib_run3` branch. I have just [committed it](https://github.com/TopEFT/topeft/commit/0c7e8079a3d24dcf45cfd0141d4f2dc66909733c). How does that sounds to you?

**Comment by bryates** [comment]
> @bryates with some GH tricks, I was able to retrieve the version in this branch and copy it into the `clib_run3` branch. I have just [committed it](https://github.com/TopEFT/topeft/commit/0c7e8079a3d24dcf45cfd0141d4f2dc66909733c). How does that sounds to you?

Thanks, but we should make changes to this PR, not to the `clib_run3` branch.

**Comment by anpicci** [comment]
@bryates Yes sure, in this way, we should avoid conflicts when merging `master` back to `clib_run3`. We will proceed to include the new line in this branch

**Comment by anpicci** [comment]
@bryates I have just pushed a commit for implementing Amanda's checking on Run3 years

**Review by anpicci — APPROVED** [review]

**Pull request merged**
